export enum Segments {
  LAUFZEITUMGEBUNGEN_JS = 'laufzeitumgebungenJS.json',
  NPM = 'npm.json',
  NODE_JS = 'nodeJs.json',
  ZUGRIFF_DATEISYSTEM = 'zugriffDateisystem.json',
  HTTP_MODULE = 'httpModule.json',
  WEBSOCKET = 'webSocket.json',
  TEMPLATE_ENGINES = 'templateEngines.json',
  ROUTING = 'routing.json',
  MODULE = 'module.json',
  HTTPS = 'https.json',
  EXPRESS_JS = 'expressJS.json',
  EVENT_DRIVEN_IPC = 'eventdrivenIPC.json',
  SQL_DATENBANK = 'sqlDatenbank.json',
  REST_CRUD = 'restCrud.json',
  PROZESSE_SUBPROZESSE = 'prozesseSubprozesse.json',
  AUTH_JWT = 'authJWT.json',
  NOSQL_DATENBANK = 'noSqlDatenbank.json',
  CICD = 'cicd.json',
  AGILES_PROJECTMANAGEMENT = 'agilesprojectmanagement.json',
  LASTENHEFT = 'lastenheft.json',
  MVC = 'mvc.json',
  POSTMAN = 'postman.json',
  REQUIERMENT_ENGINEERING = 'requirementengineering.json',
  SMCGIT = 'smcgit.json',
  TESTDRIVEN = 'testdriven.json',
  UIUX = 'uiux.json',
  WIREFRAMES = 'wireframes.json',
  HTTP_REQHEAD = 'httprequestheaders.json',
  HTTP_STATUS = 'httpstatuscode.json',
  //
  AJAXXHRCORS = 'ajaxxhrcors.json',
  ARRAYMETHODEN = 'arraymethoden.json',
  ARRAYS = 'arrays.json',
  ARROWFUNCTIONS = 'arrowfunctions.json',
  CLOSUREFUNKTIONEN = 'closurefunktionen.json',
  DATEOBJEKT = 'dateobjekt.json',
  DOMELEMENTEERZEUGEN = 'domelementeerzeugen.json',
  DOMMANIPULATION = 'dommanipulation.json',
  ERRORHANDLING = 'errorhandling.json',
  ES6 = 'es6.json',
  EVENTHANDLING = 'eventhandling.json',
  FILEREADER = 'filereader.json',
  FORMULARFELDER = 'formularfelder.json',
  JSONXMLCSV = 'jsonxmlcsv.json',
  KLASSENSUBKLASSEN = 'klassensubklassen.json',
  MAPSETSSYMBOL = 'mapsetssymbol.json',
  METHODCHAINING = 'methodchaining.json',
  OBJECTPROPERTIES = 'objectproperties.json',
  OBJEKTE = 'objekte.json',
  OOP = 'oop.json',
  PROMISE = 'promise.json',
  QUERYSTRING = 'querystring.json',
  REGEX = 'regex.json',
  SETTERGETTER = 'settergetter.json',
  SPA = 'spa.json',
  STORAGEINBROWSER = 'storegeinbrowser.json',
  STRINGMETHODEN = 'stringmethoden.json',
  SYNCASYNCABLAUFE = 'syncasyncablaufe.json',
  TASTATUREREIGNISSE = 'tastaturereignisse.json',
  THIS = 'this.json',
  WEBWORKER = 'webworker.json',
  ZEITFUNKTIONEN = 'zeitfunktionen.json',
  REACT_GRUNDLAGEN = 'reactGrundlagen.json',
  REACT_KOMPONENTEN = 'reactKomponenten.json',
  REACT_KOMPONENTEN_EIGENSCHAFEN = 'reactKomponentenEigenschaften.json',
  REACT_LEBENZYKLUS_METHODEN = 'reactLebenzyklusMethoden.json',
  REACT_ROUTER = 'reactRouter.json',
  REACT_UNITESTING = 'reactUnitesting.json',
  REFERENZEN = 'referenzen.json',
  JSX = 'jsx.json',
  HOOKS = 'hooks.json',
  FORMULARE = 'formulare.json',
  CONTEXT = 'context.json',
  HIGHER_ORDER_KOMPONENTEN = 'higherOrderKomponenten.json',
  STATE_LOKALER_STATUS = 'stateLokalerStatus.json',
  STATE_MNG_REDUX_MIDDLEWARE = 'stateMngReduxMiddleware.json',
  UMGEBUNGSVARIABLEN_DEV_PROD = 'umgebungsvariablenDevPro.json',
  KOMPONENTEN_STYLING_CSS_MODULE = 'komponentenStylingCssModule.json',
  BEHANDLUNG_EVENTS = 'behandlungEvents.json',
  BEDINGTES_RENDERING = 'bedingtesRendering.json',
  ASYNCHRONE_DATEN_IN_REACT = 'asynchroneDatenInReact.json',
  ARRAY_RENDERING_AUFLISTUNGEN = 'arrayRenderingAuflistungen.json'
}

export const ALL_SEGMENTS = [
  Segments.AJAXXHRCORS,
  Segments.NOSQL_DATENBANK,
  Segments.ARRAYMETHODEN,
  Segments.ARRAYS,
  Segments.ARROWFUNCTIONS,
  Segments.CLOSUREFUNKTIONEN,
  Segments.DATEOBJEKT,
  Segments.DOMELEMENTEERZEUGEN,
  Segments.DOMMANIPULATION,
  Segments.ERRORHANDLING,
  Segments.ES6,
  Segments.EVENTHANDLING,
  Segments.FILEREADER,
  Segments.FORMULARFELDER,
  Segments.JSONXMLCSV,
  Segments.KLASSENSUBKLASSEN,
  Segments.MAPSETSSYMBOL,
  Segments.METHODCHAINING,
  Segments.OBJECTPROPERTIES,
  Segments.OBJEKTE,
  Segments.OOP,
  Segments.PROMISE,
  Segments.QUERYSTRING,
  Segments.REGEX,
  Segments.SETTERGETTER,
  Segments.SPA,
  Segments.STORAGEINBROWSER,
  Segments.STRINGMETHODEN,
  Segments.SYNCASYNCABLAUFE,
  Segments.TASTATUREREIGNISSE,
  Segments.THIS,
  Segments.WEBWORKER,
  Segments.ZEITFUNKTIONEN,
  Segments.LAUFZEITUMGEBUNGEN_JS,
  Segments.NPM,
  Segments.NODE_JS,
  Segments.ZUGRIFF_DATEISYSTEM,
  Segments.HTTP_MODULE,
  Segments.WEBSOCKET,
  Segments.TEMPLATE_ENGINES,
  Segments.ROUTING,
  Segments.MODULE,
  Segments.HTTPS,
  Segments.EXPRESS_JS,
  Segments.EVENT_DRIVEN_IPC,
  Segments.SQL_DATENBANK,
  Segments.REST_CRUD,
  Segments.PROZESSE_SUBPROZESSE,
  Segments.AUTH_JWT,
  Segments.CICD,
  Segments.AGILES_PROJECTMANAGEMENT,
  Segments.LASTENHEFT,
  Segments.MVC,
  Segments.POSTMAN,
  Segments.REQUIERMENT_ENGINEERING,
  Segments.SMCGIT,
  Segments.TESTDRIVEN,
  Segments.UIUX,
  Segments.WIREFRAMES,
  Segments.HTTP_REQHEAD,
  Segments.REACT_GRUNDLAGEN,
  Segments.REACT_KOMPONENTEN,
  Segments.REACT_KOMPONENTEN_EIGENSCHAFEN,
  Segments.REACT_LEBENZYKLUS_METHODEN,
  Segments.REACT_ROUTER,
  Segments.REACT_UNITESTING,
  Segments.REFERENZEN,
  Segments.JSX,
  Segments.HOOKS,
  Segments.FORMULARE,
  Segments.CONTEXT,
  Segments.HIGHER_ORDER_KOMPONENTEN,
  Segments.STATE_LOKALER_STATUS,
  Segments.STATE_MNG_REDUX_MIDDLEWARE,
  Segments.UMGEBUNGSVARIABLEN_DEV_PROD,
  Segments.KOMPONENTEN_STYLING_CSS_MODULE,
  Segments.BEHANDLUNG_EVENTS,
  Segments.BEDINGTES_RENDERING,
  Segments.ASYNCHRONE_DATEN_IN_REACT,
  Segments.ARRAY_RENDERING_AUFLISTUNGEN
];




