export enum Segments {
  LAUFZEITUMGEBUNGEN_JS = 'laufzeitumgebungenJS.json',
  NPM = 'npm.json',
  NODE_JS = 'nodeJs.json',
  ZUGRIFF_DATEISYSTEM = 'zugriffDateisystem.json',
  HTTP_MODULE = 'httpModule.json',
  WEBSOCKET = 'webSocket.json',
  TEMPLATE_ENGINES = 'templateEngines.json',
  ROUTING = 'routing.json',
  MODULE = 'module.json',
  HTTPS = 'https.json',
  EXPRESS_JS = 'expressJS.json',
  EVENT_DRIVEN_IPC = 'eventdrivenIPC.json',
  SQL_DATENBANK = 'sqlDatenbank.json',
  REST_CRUD = 'restCrud.json',
  PROZESSE_SUBPROZESSE = 'prozesseSubprozesse.json',
  AUTH_JWT = 'authJWT.json',
  NOSQL_DATENBANK = 'noSqlDatenbank.json',
  CICD = 'cicd.json',
  AGILES_PROJECTMANAGEMENT = 'agilesprojectmanagement.json',
  LASTENHEFT = 'lastenheft.json',
  MVC = 'mvc.json',
  POSTMAN = 'postman.json',
  REQUIERMENT_ENGINEERING = 'requirement_engineering.json',
  SMCGIT = 'smcgit.json',
  TESTDRIVEN = 'testdriven.json',
  UIUX = 'uiux.json',
  WIREFRAMES = 'wireframes.json',
}

export const ALL_SEGMENTS = [
  Segments.LAUFZEITUMGEBUNGEN_JS,
  Segments.NPM,
  Segments.NODE_JS,
  Segments.ZUGRIFF_DATEISYSTEM,
  Segments.HTTP_MODULE,
  Segments.WEBSOCKET,
  Segments.TEMPLATE_ENGINES,
  Segments.ROUTING,
  Segments.MODULE,
  Segments.HTTPS,
  Segments.EXPRESS_JS,
  Segments.EVENT_DRIVEN_IPC,
  Segments.SQL_DATENBANK,
  Segments.REST_CRUD,
  Segments.PROZESSE_SUBPROZESSE,
  Segments.AUTH_JWT,
  Segments.CICD,
  Segments.AGILES_PROJECTMANAGEMENT,
  Segments.LASTENHEFT,
  Segments.MVC,
  Segments.POSTMAN,
  Segments.REQUIERMENT_ENGINEERING,
  Segments.SMCGIT,
  Segments.TESTDRIVEN,
  Segments.UIUX,
  Segments.WIREFRAMES,
];
